name: Test, Build, Push to Google Cloud Run


on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'fixYaml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run tests
        env:
          MODE: 'github actions'
        run: |
          pytest
